import React from 'react';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs'
import ThemeProvider from '@/providers/theme-provider';
import LayoutProvider from '@/providers/layout-provider';
import ReduxProvider from '@/providers/redux-provider';
import './globals.css';
import 'remixicon/fonts/remixicon.css'

export const metadata: Metadata = {
  title: 'NextJS - SocketIO Chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider>
            <ReduxProvider>
              <LayoutProvider>{children}</LayoutProvider>
            </ReduxProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
