import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css';
import ThemeProvider from '@/providers/theme-provider';

export const metadata: Metadata = {
  title: 'NextJS - SocketIO Chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
